//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI1.Sw_Pro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://controller/", ConfigurationName="Sw_Pro.Controller")]
    public interface Controller {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/listarOrdenesPorIdProductoRequest", ReplyAction="http://controller/Controller/listarOrdenesPorIdProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.listarOrdenesPorIdProductoResponse listarOrdenesPorIdProducto(GUI1.Sw_Pro.listarOrdenesPorIdProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/listarOrdenesPorIdProductoRequest", ReplyAction="http://controller/Controller/listarOrdenesPorIdProductoResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.listarOrdenesPorIdProductoResponse> listarOrdenesPorIdProductoAsync(GUI1.Sw_Pro.listarOrdenesPorIdProductoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/listarProductosPorNombreRequest", ReplyAction="http://controller/Controller/listarProductosPorNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.listarProductosPorNombreResponse listarProductosPorNombre(GUI1.Sw_Pro.listarProductosPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/listarProductosPorNombreRequest", ReplyAction="http://controller/Controller/listarProductosPorNombreResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.listarProductosPorNombreResponse> listarProductosPorNombreAsync(GUI1.Sw_Pro.listarProductosPorNombreRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/obtenerProductoRequest", ReplyAction="http://controller/Controller/obtenerProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.obtenerProductoResponse obtenerProducto(GUI1.Sw_Pro.obtenerProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/obtenerProductoRequest", ReplyAction="http://controller/Controller/obtenerProductoResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.obtenerProductoResponse> obtenerProductoAsync(GUI1.Sw_Pro.obtenerProductoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/obtenerOrdenRequest", ReplyAction="http://controller/Controller/obtenerOrdenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.obtenerOrdenResponse obtenerOrden(GUI1.Sw_Pro.obtenerOrdenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/obtenerOrdenRequest", ReplyAction="http://controller/Controller/obtenerOrdenResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.obtenerOrdenResponse> obtenerOrdenAsync(GUI1.Sw_Pro.obtenerOrdenRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/listarPreciosRequest", ReplyAction="http://controller/Controller/listarPreciosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.listarPreciosResponse listarPrecios(GUI1.Sw_Pro.listarPreciosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/listarPreciosRequest", ReplyAction="http://controller/Controller/listarPreciosResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.listarPreciosResponse> listarPreciosAsync(GUI1.Sw_Pro.listarPreciosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/guardarOrdenRequest", ReplyAction="http://controller/Controller/guardarOrdenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.guardarOrdenResponse guardarOrden(GUI1.Sw_Pro.guardarOrdenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/guardarOrdenRequest", ReplyAction="http://controller/Controller/guardarOrdenResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.guardarOrdenResponse> guardarOrdenAsync(GUI1.Sw_Pro.guardarOrdenRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/guardarProductoRequest", ReplyAction="http://controller/Controller/guardarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.guardarProductoResponse guardarProducto(GUI1.Sw_Pro.guardarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/guardarProductoRequest", ReplyAction="http://controller/Controller/guardarProductoResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.guardarProductoResponse> guardarProductoAsync(GUI1.Sw_Pro.guardarProductoRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/actualizarPrecioVentaProductoRequest", ReplyAction="http://controller/Controller/actualizarPrecioVentaProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GUI1.Sw_Pro.actualizarPrecioVentaProductoResponse actualizarPrecioVentaProducto(GUI1.Sw_Pro.actualizarPrecioVentaProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/actualizarPrecioVentaProductoRequest", ReplyAction="http://controller/Controller/actualizarPrecioVentaProductoResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.actualizarPrecioVentaProductoResponse> actualizarPrecioVentaProductoAsync(GUI1.Sw_Pro.actualizarPrecioVentaProductoRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/actualizarCatntidadOrdenRequest", ReplyAction="http://controller/Controller/actualizarCatntidadOrdenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GUI1.Sw_Pro.actualizarCatntidadOrdenResponse actualizarCatntidadOrden(GUI1.Sw_Pro.actualizarCatntidadOrdenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/actualizarCatntidadOrdenRequest", ReplyAction="http://controller/Controller/actualizarCatntidadOrdenResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.actualizarCatntidadOrdenResponse> actualizarCatntidadOrdenAsync(GUI1.Sw_Pro.actualizarCatntidadOrdenRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/eliminarOrdenPorIdRequest", ReplyAction="http://controller/Controller/eliminarOrdenPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.eliminarOrdenPorIdResponse eliminarOrdenPorId(GUI1.Sw_Pro.eliminarOrdenPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/eliminarOrdenPorIdRequest", ReplyAction="http://controller/Controller/eliminarOrdenPorIdResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.eliminarOrdenPorIdResponse> eliminarOrdenPorIdAsync(GUI1.Sw_Pro.eliminarOrdenPorIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/eliminarProductoPorIdRequest", ReplyAction="http://controller/Controller/eliminarProductoPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.eliminarProductoPorIdResponse eliminarProductoPorId(GUI1.Sw_Pro.eliminarProductoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller/Controller/eliminarProductoPorIdRequest", ReplyAction="http://controller/Controller/eliminarProductoPorIdResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.eliminarProductoPorIdResponse> eliminarProductoPorIdAsync(GUI1.Sw_Pro.eliminarProductoPorIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller/")]
    public partial class orden : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private int pedidoIdField;
        
        private bool pedidoIdFieldSpecified;
        
        private double precioField;
        
        private bool precioFieldSpecified;
        
        private producto productoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
                this.RaisePropertyChanged("cantidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int pedidoId {
            get {
                return this.pedidoIdField;
            }
            set {
                this.pedidoIdField = value;
                this.RaisePropertyChanged("pedidoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pedidoIdSpecified {
            get {
                return this.pedidoIdFieldSpecified;
            }
            set {
                this.pedidoIdFieldSpecified = value;
                this.RaisePropertyChanged("pedidoIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioSpecified {
            get {
                return this.precioFieldSpecified;
            }
            set {
                this.precioFieldSpecified = value;
                this.RaisePropertyChanged("precioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller/")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private string nombreField;
        
        private orden[] ordenesField;
        
        private double precioVentaField;
        
        private bool precioVentaFieldSpecified;
        
        private long upcField;
        
        private bool upcFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ordenes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public orden[] ordenes {
            get {
                return this.ordenesField;
            }
            set {
                this.ordenesField = value;
                this.RaisePropertyChanged("ordenes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double precioVenta {
            get {
                return this.precioVentaField;
            }
            set {
                this.precioVentaField = value;
                this.RaisePropertyChanged("precioVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioVentaSpecified {
            get {
                return this.precioVentaFieldSpecified;
            }
            set {
                this.precioVentaFieldSpecified = value;
                this.RaisePropertyChanged("precioVentaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long upc {
            get {
                return this.upcField;
            }
            set {
                this.upcField = value;
                this.RaisePropertyChanged("upc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool upcSpecified {
            get {
                return this.upcFieldSpecified;
            }
            set {
                this.upcFieldSpecified = value;
                this.RaisePropertyChanged("upcSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesPorIdProducto", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class listarOrdenesPorIdProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public listarOrdenesPorIdProductoRequest() {
        }
        
        public listarOrdenesPorIdProductoRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesPorIdProductoResponse", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class listarOrdenesPorIdProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GUI1.Sw_Pro.orden[] @return;
        
        public listarOrdenesPorIdProductoResponse() {
        }
        
        public listarOrdenesPorIdProductoResponse(GUI1.Sw_Pro.orden[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosPorNombre", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class listarProductosPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public listarProductosPorNombreRequest() {
        }
        
        public listarProductosPorNombreRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosPorNombreResponse", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class listarProductosPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GUI1.Sw_Pro.producto[] @return;
        
        public listarProductosPorNombreResponse() {
        }
        
        public listarProductosPorNombreResponse(GUI1.Sw_Pro.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProducto", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class obtenerProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public obtenerProductoRequest() {
        }
        
        public obtenerProductoRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProductoResponse", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class obtenerProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GUI1.Sw_Pro.producto @return;
        
        public obtenerProductoResponse() {
        }
        
        public obtenerProductoResponse(GUI1.Sw_Pro.producto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerOrden", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class obtenerOrdenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public obtenerOrdenRequest() {
        }
        
        public obtenerOrdenRequest(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerOrdenResponse", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class obtenerOrdenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GUI1.Sw_Pro.orden @return;
        
        public obtenerOrdenResponse() {
        }
        
        public obtenerOrdenResponse(GUI1.Sw_Pro.orden @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://controller/")]
    public partial class listarPreciosResponseEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int keyField;
        
        private bool keyFieldSpecified;
        
        private int valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool keySpecified {
            get {
                return this.keyFieldSpecified;
            }
            set {
                this.keyFieldSpecified = value;
                this.RaisePropertyChanged("keySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
                this.RaisePropertyChanged("valueSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrecios", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class listarPreciosRequest {
        
        public listarPreciosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPreciosResponse", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class listarPreciosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GUI1.Sw_Pro.listarPreciosResponseEntry[] @return;
        
        public listarPreciosResponse() {
        }
        
        public listarPreciosResponse(GUI1.Sw_Pro.listarPreciosResponseEntry[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarOrden", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class guardarOrdenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GUI1.Sw_Pro.orden orden;
        
        public guardarOrdenRequest() {
        }
        
        public guardarOrdenRequest(GUI1.Sw_Pro.orden orden) {
            this.orden = orden;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarOrdenResponse", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class guardarOrdenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public guardarOrdenResponse() {
        }
        
        public guardarOrdenResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarProducto", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class guardarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GUI1.Sw_Pro.producto arg0;
        
        public guardarProductoRequest() {
        }
        
        public guardarProductoRequest(GUI1.Sw_Pro.producto arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarProductoResponse", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class guardarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public guardarProductoResponse() {
        }
        
        public guardarProductoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarPrecioVentaProducto", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class actualizarPrecioVentaProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GUI1.Sw_Pro.producto arg1;
        
        public actualizarPrecioVentaProductoRequest() {
        }
        
        public actualizarPrecioVentaProductoRequest(int arg0, GUI1.Sw_Pro.producto arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarPrecioVentaProductoResponse", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class actualizarPrecioVentaProductoResponse {
        
        public actualizarPrecioVentaProductoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarCatntidadOrden", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class actualizarCatntidadOrdenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GUI1.Sw_Pro.orden arg2;
        
        public actualizarCatntidadOrdenRequest() {
        }
        
        public actualizarCatntidadOrdenRequest(int arg0, int arg1, GUI1.Sw_Pro.orden arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarCatntidadOrdenResponse", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class actualizarCatntidadOrdenResponse {
        
        public actualizarCatntidadOrdenResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOrdenPorId", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class eliminarOrdenPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public eliminarOrdenPorIdRequest() {
        }
        
        public eliminarOrdenPorIdRequest(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOrdenPorIdResponse", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class eliminarOrdenPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public eliminarOrdenPorIdResponse() {
        }
        
        public eliminarOrdenPorIdResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProductoPorId", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class eliminarProductoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminarProductoPorIdRequest() {
        }
        
        public eliminarProductoPorIdRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProductoPorIdResponse", WrapperNamespace="http://controller/", IsWrapped=true)]
    public partial class eliminarProductoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public eliminarProductoPorIdResponse() {
        }
        
        public eliminarProductoPorIdResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ControllerChannel : GUI1.Sw_Pro.Controller, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControllerClient : System.ServiceModel.ClientBase<GUI1.Sw_Pro.Controller>, GUI1.Sw_Pro.Controller {
        
        public ControllerClient() {
        }
        
        public ControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.listarOrdenesPorIdProductoResponse GUI1.Sw_Pro.Controller.listarOrdenesPorIdProducto(GUI1.Sw_Pro.listarOrdenesPorIdProductoRequest request) {
            return base.Channel.listarOrdenesPorIdProducto(request);
        }
        
        public GUI1.Sw_Pro.orden[] listarOrdenesPorIdProducto(string arg0) {
            GUI1.Sw_Pro.listarOrdenesPorIdProductoRequest inValue = new GUI1.Sw_Pro.listarOrdenesPorIdProductoRequest();
            inValue.arg0 = arg0;
            GUI1.Sw_Pro.listarOrdenesPorIdProductoResponse retVal = ((GUI1.Sw_Pro.Controller)(this)).listarOrdenesPorIdProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.listarOrdenesPorIdProductoResponse> GUI1.Sw_Pro.Controller.listarOrdenesPorIdProductoAsync(GUI1.Sw_Pro.listarOrdenesPorIdProductoRequest request) {
            return base.Channel.listarOrdenesPorIdProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.listarOrdenesPorIdProductoResponse> listarOrdenesPorIdProductoAsync(string arg0) {
            GUI1.Sw_Pro.listarOrdenesPorIdProductoRequest inValue = new GUI1.Sw_Pro.listarOrdenesPorIdProductoRequest();
            inValue.arg0 = arg0;
            return ((GUI1.Sw_Pro.Controller)(this)).listarOrdenesPorIdProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.listarProductosPorNombreResponse GUI1.Sw_Pro.Controller.listarProductosPorNombre(GUI1.Sw_Pro.listarProductosPorNombreRequest request) {
            return base.Channel.listarProductosPorNombre(request);
        }
        
        public GUI1.Sw_Pro.producto[] listarProductosPorNombre(string arg0) {
            GUI1.Sw_Pro.listarProductosPorNombreRequest inValue = new GUI1.Sw_Pro.listarProductosPorNombreRequest();
            inValue.arg0 = arg0;
            GUI1.Sw_Pro.listarProductosPorNombreResponse retVal = ((GUI1.Sw_Pro.Controller)(this)).listarProductosPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.listarProductosPorNombreResponse> GUI1.Sw_Pro.Controller.listarProductosPorNombreAsync(GUI1.Sw_Pro.listarProductosPorNombreRequest request) {
            return base.Channel.listarProductosPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.listarProductosPorNombreResponse> listarProductosPorNombreAsync(string arg0) {
            GUI1.Sw_Pro.listarProductosPorNombreRequest inValue = new GUI1.Sw_Pro.listarProductosPorNombreRequest();
            inValue.arg0 = arg0;
            return ((GUI1.Sw_Pro.Controller)(this)).listarProductosPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.obtenerProductoResponse GUI1.Sw_Pro.Controller.obtenerProducto(GUI1.Sw_Pro.obtenerProductoRequest request) {
            return base.Channel.obtenerProducto(request);
        }
        
        public GUI1.Sw_Pro.producto obtenerProducto(int arg0) {
            GUI1.Sw_Pro.obtenerProductoRequest inValue = new GUI1.Sw_Pro.obtenerProductoRequest();
            inValue.arg0 = arg0;
            GUI1.Sw_Pro.obtenerProductoResponse retVal = ((GUI1.Sw_Pro.Controller)(this)).obtenerProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.obtenerProductoResponse> GUI1.Sw_Pro.Controller.obtenerProductoAsync(GUI1.Sw_Pro.obtenerProductoRequest request) {
            return base.Channel.obtenerProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.obtenerProductoResponse> obtenerProductoAsync(int arg0) {
            GUI1.Sw_Pro.obtenerProductoRequest inValue = new GUI1.Sw_Pro.obtenerProductoRequest();
            inValue.arg0 = arg0;
            return ((GUI1.Sw_Pro.Controller)(this)).obtenerProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.obtenerOrdenResponse GUI1.Sw_Pro.Controller.obtenerOrden(GUI1.Sw_Pro.obtenerOrdenRequest request) {
            return base.Channel.obtenerOrden(request);
        }
        
        public GUI1.Sw_Pro.orden obtenerOrden(int arg0, int arg1) {
            GUI1.Sw_Pro.obtenerOrdenRequest inValue = new GUI1.Sw_Pro.obtenerOrdenRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            GUI1.Sw_Pro.obtenerOrdenResponse retVal = ((GUI1.Sw_Pro.Controller)(this)).obtenerOrden(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.obtenerOrdenResponse> GUI1.Sw_Pro.Controller.obtenerOrdenAsync(GUI1.Sw_Pro.obtenerOrdenRequest request) {
            return base.Channel.obtenerOrdenAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.obtenerOrdenResponse> obtenerOrdenAsync(int arg0, int arg1) {
            GUI1.Sw_Pro.obtenerOrdenRequest inValue = new GUI1.Sw_Pro.obtenerOrdenRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((GUI1.Sw_Pro.Controller)(this)).obtenerOrdenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.listarPreciosResponse GUI1.Sw_Pro.Controller.listarPrecios(GUI1.Sw_Pro.listarPreciosRequest request) {
            return base.Channel.listarPrecios(request);
        }
        
        public GUI1.Sw_Pro.listarPreciosResponseEntry[] listarPrecios() {
            GUI1.Sw_Pro.listarPreciosRequest inValue = new GUI1.Sw_Pro.listarPreciosRequest();
            GUI1.Sw_Pro.listarPreciosResponse retVal = ((GUI1.Sw_Pro.Controller)(this)).listarPrecios(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.listarPreciosResponse> GUI1.Sw_Pro.Controller.listarPreciosAsync(GUI1.Sw_Pro.listarPreciosRequest request) {
            return base.Channel.listarPreciosAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.listarPreciosResponse> listarPreciosAsync() {
            GUI1.Sw_Pro.listarPreciosRequest inValue = new GUI1.Sw_Pro.listarPreciosRequest();
            return ((GUI1.Sw_Pro.Controller)(this)).listarPreciosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.guardarOrdenResponse GUI1.Sw_Pro.Controller.guardarOrden(GUI1.Sw_Pro.guardarOrdenRequest request) {
            return base.Channel.guardarOrden(request);
        }
        
        public bool guardarOrden(GUI1.Sw_Pro.orden orden) {
            GUI1.Sw_Pro.guardarOrdenRequest inValue = new GUI1.Sw_Pro.guardarOrdenRequest();
            inValue.orden = orden;
            GUI1.Sw_Pro.guardarOrdenResponse retVal = ((GUI1.Sw_Pro.Controller)(this)).guardarOrden(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.guardarOrdenResponse> GUI1.Sw_Pro.Controller.guardarOrdenAsync(GUI1.Sw_Pro.guardarOrdenRequest request) {
            return base.Channel.guardarOrdenAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.guardarOrdenResponse> guardarOrdenAsync(GUI1.Sw_Pro.orden orden) {
            GUI1.Sw_Pro.guardarOrdenRequest inValue = new GUI1.Sw_Pro.guardarOrdenRequest();
            inValue.orden = orden;
            return ((GUI1.Sw_Pro.Controller)(this)).guardarOrdenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.guardarProductoResponse GUI1.Sw_Pro.Controller.guardarProducto(GUI1.Sw_Pro.guardarProductoRequest request) {
            return base.Channel.guardarProducto(request);
        }
        
        public bool guardarProducto(GUI1.Sw_Pro.producto arg0) {
            GUI1.Sw_Pro.guardarProductoRequest inValue = new GUI1.Sw_Pro.guardarProductoRequest();
            inValue.arg0 = arg0;
            GUI1.Sw_Pro.guardarProductoResponse retVal = ((GUI1.Sw_Pro.Controller)(this)).guardarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.guardarProductoResponse> GUI1.Sw_Pro.Controller.guardarProductoAsync(GUI1.Sw_Pro.guardarProductoRequest request) {
            return base.Channel.guardarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.guardarProductoResponse> guardarProductoAsync(GUI1.Sw_Pro.producto arg0) {
            GUI1.Sw_Pro.guardarProductoRequest inValue = new GUI1.Sw_Pro.guardarProductoRequest();
            inValue.arg0 = arg0;
            return ((GUI1.Sw_Pro.Controller)(this)).guardarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.actualizarPrecioVentaProductoResponse GUI1.Sw_Pro.Controller.actualizarPrecioVentaProducto(GUI1.Sw_Pro.actualizarPrecioVentaProductoRequest request) {
            return base.Channel.actualizarPrecioVentaProducto(request);
        }
        
        public void actualizarPrecioVentaProducto(int arg0, GUI1.Sw_Pro.producto arg1) {
            GUI1.Sw_Pro.actualizarPrecioVentaProductoRequest inValue = new GUI1.Sw_Pro.actualizarPrecioVentaProductoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            GUI1.Sw_Pro.actualizarPrecioVentaProductoResponse retVal = ((GUI1.Sw_Pro.Controller)(this)).actualizarPrecioVentaProducto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.actualizarPrecioVentaProductoResponse> GUI1.Sw_Pro.Controller.actualizarPrecioVentaProductoAsync(GUI1.Sw_Pro.actualizarPrecioVentaProductoRequest request) {
            return base.Channel.actualizarPrecioVentaProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.actualizarPrecioVentaProductoResponse> actualizarPrecioVentaProductoAsync(int arg0, GUI1.Sw_Pro.producto arg1) {
            GUI1.Sw_Pro.actualizarPrecioVentaProductoRequest inValue = new GUI1.Sw_Pro.actualizarPrecioVentaProductoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((GUI1.Sw_Pro.Controller)(this)).actualizarPrecioVentaProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.actualizarCatntidadOrdenResponse GUI1.Sw_Pro.Controller.actualizarCatntidadOrden(GUI1.Sw_Pro.actualizarCatntidadOrdenRequest request) {
            return base.Channel.actualizarCatntidadOrden(request);
        }
        
        public void actualizarCatntidadOrden(int arg0, int arg1, GUI1.Sw_Pro.orden arg2) {
            GUI1.Sw_Pro.actualizarCatntidadOrdenRequest inValue = new GUI1.Sw_Pro.actualizarCatntidadOrdenRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            GUI1.Sw_Pro.actualizarCatntidadOrdenResponse retVal = ((GUI1.Sw_Pro.Controller)(this)).actualizarCatntidadOrden(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.actualizarCatntidadOrdenResponse> GUI1.Sw_Pro.Controller.actualizarCatntidadOrdenAsync(GUI1.Sw_Pro.actualizarCatntidadOrdenRequest request) {
            return base.Channel.actualizarCatntidadOrdenAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.actualizarCatntidadOrdenResponse> actualizarCatntidadOrdenAsync(int arg0, int arg1, GUI1.Sw_Pro.orden arg2) {
            GUI1.Sw_Pro.actualizarCatntidadOrdenRequest inValue = new GUI1.Sw_Pro.actualizarCatntidadOrdenRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((GUI1.Sw_Pro.Controller)(this)).actualizarCatntidadOrdenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.eliminarOrdenPorIdResponse GUI1.Sw_Pro.Controller.eliminarOrdenPorId(GUI1.Sw_Pro.eliminarOrdenPorIdRequest request) {
            return base.Channel.eliminarOrdenPorId(request);
        }
        
        public bool eliminarOrdenPorId(int arg0, int arg1) {
            GUI1.Sw_Pro.eliminarOrdenPorIdRequest inValue = new GUI1.Sw_Pro.eliminarOrdenPorIdRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            GUI1.Sw_Pro.eliminarOrdenPorIdResponse retVal = ((GUI1.Sw_Pro.Controller)(this)).eliminarOrdenPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.eliminarOrdenPorIdResponse> GUI1.Sw_Pro.Controller.eliminarOrdenPorIdAsync(GUI1.Sw_Pro.eliminarOrdenPorIdRequest request) {
            return base.Channel.eliminarOrdenPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.eliminarOrdenPorIdResponse> eliminarOrdenPorIdAsync(int arg0, int arg1) {
            GUI1.Sw_Pro.eliminarOrdenPorIdRequest inValue = new GUI1.Sw_Pro.eliminarOrdenPorIdRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((GUI1.Sw_Pro.Controller)(this)).eliminarOrdenPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.eliminarProductoPorIdResponse GUI1.Sw_Pro.Controller.eliminarProductoPorId(GUI1.Sw_Pro.eliminarProductoPorIdRequest request) {
            return base.Channel.eliminarProductoPorId(request);
        }
        
        public bool eliminarProductoPorId(int arg0) {
            GUI1.Sw_Pro.eliminarProductoPorIdRequest inValue = new GUI1.Sw_Pro.eliminarProductoPorIdRequest();
            inValue.arg0 = arg0;
            GUI1.Sw_Pro.eliminarProductoPorIdResponse retVal = ((GUI1.Sw_Pro.Controller)(this)).eliminarProductoPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.eliminarProductoPorIdResponse> GUI1.Sw_Pro.Controller.eliminarProductoPorIdAsync(GUI1.Sw_Pro.eliminarProductoPorIdRequest request) {
            return base.Channel.eliminarProductoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.eliminarProductoPorIdResponse> eliminarProductoPorIdAsync(int arg0) {
            GUI1.Sw_Pro.eliminarProductoPorIdRequest inValue = new GUI1.Sw_Pro.eliminarProductoPorIdRequest();
            inValue.arg0 = arg0;
            return ((GUI1.Sw_Pro.Controller)(this)).eliminarProductoPorIdAsync(inValue);
        }
    }
}
