//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI1.Sw_Pro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services/", ConfigurationName="Sw_Pro.SWControlador")]
    public interface SWControlador {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/listarOrdenesPorIdProductoRequest", ReplyAction="http://services/SWControlador/listarOrdenesPorIdProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.listarOrdenesPorIdProductoResponse listarOrdenesPorIdProducto(GUI1.Sw_Pro.listarOrdenesPorIdProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/listarOrdenesPorIdProductoRequest", ReplyAction="http://services/SWControlador/listarOrdenesPorIdProductoResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.listarOrdenesPorIdProductoResponse> listarOrdenesPorIdProductoAsync(GUI1.Sw_Pro.listarOrdenesPorIdProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/eliminarOrdenPorIdRequest", ReplyAction="http://services/SWControlador/eliminarOrdenPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.eliminarOrdenPorIdResponse eliminarOrdenPorId(GUI1.Sw_Pro.eliminarOrdenPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/eliminarOrdenPorIdRequest", ReplyAction="http://services/SWControlador/eliminarOrdenPorIdResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.eliminarOrdenPorIdResponse> eliminarOrdenPorIdAsync(GUI1.Sw_Pro.eliminarOrdenPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/guardarProductoPedidoRequest", ReplyAction="http://services/SWControlador/guardarProductoPedidoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.guardarProductoPedidoResponse guardarProductoPedido(GUI1.Sw_Pro.guardarProductoPedidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/guardarProductoPedidoRequest", ReplyAction="http://services/SWControlador/guardarProductoPedidoResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.guardarProductoPedidoResponse> guardarProductoPedidoAsync(GUI1.Sw_Pro.guardarProductoPedidoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/eliminarProductoPorIdRequest", ReplyAction="http://services/SWControlador/eliminarProductoPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.eliminarProductoPorIdResponse eliminarProductoPorId(GUI1.Sw_Pro.eliminarProductoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/eliminarProductoPorIdRequest", ReplyAction="http://services/SWControlador/eliminarProductoPorIdResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.eliminarProductoPorIdResponse> eliminarProductoPorIdAsync(GUI1.Sw_Pro.eliminarProductoPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/actualizarPrecioVentaProductoRequest", ReplyAction="http://services/SWControlador/actualizarPrecioVentaProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.actualizarPrecioVentaProductoResponse actualizarPrecioVentaProducto(GUI1.Sw_Pro.actualizarPrecioVentaProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/actualizarPrecioVentaProductoRequest", ReplyAction="http://services/SWControlador/actualizarPrecioVentaProductoResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.actualizarPrecioVentaProductoResponse> actualizarPrecioVentaProductoAsync(GUI1.Sw_Pro.actualizarPrecioVentaProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/listarProductosPorNombreRequest", ReplyAction="http://services/SWControlador/listarProductosPorNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.listarProductosPorNombreResponse listarProductosPorNombre(GUI1.Sw_Pro.listarProductosPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/listarProductosPorNombreRequest", ReplyAction="http://services/SWControlador/listarProductosPorNombreResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.listarProductosPorNombreResponse> listarProductosPorNombreAsync(GUI1.Sw_Pro.listarProductosPorNombreRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/actualizarOrdenRequest", ReplyAction="http://services/SWControlador/actualizarOrdenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.actualizarOrdenResponse actualizarOrden(GUI1.Sw_Pro.actualizarOrdenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/actualizarOrdenRequest", ReplyAction="http://services/SWControlador/actualizarOrdenResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.actualizarOrdenResponse> actualizarOrdenAsync(GUI1.Sw_Pro.actualizarOrdenRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/obtenerProductoRequest", ReplyAction="http://services/SWControlador/obtenerProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.obtenerProductoResponse obtenerProducto(GUI1.Sw_Pro.obtenerProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/obtenerProductoRequest", ReplyAction="http://services/SWControlador/obtenerProductoResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.obtenerProductoResponse> obtenerProductoAsync(GUI1.Sw_Pro.obtenerProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/buscarProductoPedidoRequest", ReplyAction="http://services/SWControlador/buscarProductoPedidoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.buscarProductoPedidoResponse buscarProductoPedido(GUI1.Sw_Pro.buscarProductoPedidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/buscarProductoPedidoRequest", ReplyAction="http://services/SWControlador/buscarProductoPedidoResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.buscarProductoPedidoResponse> buscarProductoPedidoAsync(GUI1.Sw_Pro.buscarProductoPedidoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/guardarProductoRequest", ReplyAction="http://services/SWControlador/guardarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.guardarProductoResponse guardarProducto(GUI1.Sw_Pro.guardarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/guardarProductoRequest", ReplyAction="http://services/SWControlador/guardarProductoResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.guardarProductoResponse> guardarProductoAsync(GUI1.Sw_Pro.guardarProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/listarOrdenesRequest", ReplyAction="http://services/SWControlador/listarOrdenesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GUI1.Sw_Pro.listarOrdenesResponse listarOrdenes(GUI1.Sw_Pro.listarOrdenesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/SWControlador/listarOrdenesRequest", ReplyAction="http://services/SWControlador/listarOrdenesResponse")]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.listarOrdenesResponse> listarOrdenesAsync(GUI1.Sw_Pro.listarOrdenesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services/")]
    public partial class productosPedidos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short cantidadField;
        
        private pedidos pedidosField;
        
        private string precioField;
        
        private producto productoField;
        
        private productosPedidosPK productosPedidosPKField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public short cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public pedidos pedidos {
            get {
                return this.pedidosField;
            }
            set {
                this.pedidosField = value;
                this.RaisePropertyChanged("pedidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public productosPedidosPK productosPedidosPK {
            get {
                return this.productosPedidosPKField;
            }
            set {
                this.productosPedidosPKField = value;
                this.RaisePropertyChanged("productosPedidosPK");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services/")]
    public partial class pedidos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private string guiaField;
        
        private decimal idPedidoField;
        
        private bool idPedidoFieldSpecified;
        
        private long precioEnvioField;
        
        private long precioImpuestosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string guia {
            get {
                return this.guiaField;
            }
            set {
                this.guiaField = value;
                this.RaisePropertyChanged("guia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal idPedido {
            get {
                return this.idPedidoField;
            }
            set {
                this.idPedidoField = value;
                this.RaisePropertyChanged("idPedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPedidoSpecified {
            get {
                return this.idPedidoFieldSpecified;
            }
            set {
                this.idPedidoFieldSpecified = value;
                this.RaisePropertyChanged("idPedidoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long precioEnvio {
            get {
                return this.precioEnvioField;
            }
            set {
                this.precioEnvioField = value;
                this.RaisePropertyChanged("precioEnvio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long precioImpuestos {
            get {
                return this.precioImpuestosField;
            }
            set {
                this.precioImpuestosField = value;
                this.RaisePropertyChanged("precioImpuestos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services/")]
    public partial class productosPedidosPK : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pedidosidPedidoField;
        
        private long productoidProductoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string pedidosidPedido {
            get {
                return this.pedidosidPedidoField;
            }
            set {
                this.pedidosidPedidoField = value;
                this.RaisePropertyChanged("pedidosidPedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long productoidProducto {
            get {
                return this.productoidProductoField;
            }
            set {
                this.productoidProductoField = value;
                this.RaisePropertyChanged("productoidProducto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services/")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private string nombreField;
        
        private long precioVentaField;
        
        private string upcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long precioVenta {
            get {
                return this.precioVentaField;
            }
            set {
                this.precioVentaField = value;
                this.RaisePropertyChanged("precioVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=3)]
        public string upc {
            get {
                return this.upcField;
            }
            set {
                this.upcField = value;
                this.RaisePropertyChanged("upc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesPorIdProducto", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class listarOrdenesPorIdProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idProducto;
        
        public listarOrdenesPorIdProductoRequest() {
        }
        
        public listarOrdenesPorIdProductoRequest(long idProducto) {
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesPorIdProductoResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class listarOrdenesPorIdProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GUI1.Sw_Pro.productosPedidos[] @return;
        
        public listarOrdenesPorIdProductoResponse() {
        }
        
        public listarOrdenesPorIdProductoResponse(GUI1.Sw_Pro.productosPedidos[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOrdenPorId", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class eliminarOrdenPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idPedido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idProducto;
        
        public eliminarOrdenPorIdRequest() {
        }
        
        public eliminarOrdenPorIdRequest(long idPedido, long idProducto) {
            this.idPedido = idPedido;
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOrdenPorIdResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class eliminarOrdenPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public eliminarOrdenPorIdResponse() {
        }
        
        public eliminarOrdenPorIdResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarProductoPedido", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class guardarProductoPedidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GUI1.Sw_Pro.productosPedidos productoPedido;
        
        public guardarProductoPedidoRequest() {
        }
        
        public guardarProductoPedidoRequest(GUI1.Sw_Pro.productosPedidos productoPedido) {
            this.productoPedido = productoPedido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarProductoPedidoResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class guardarProductoPedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public guardarProductoPedidoResponse() {
        }
        
        public guardarProductoPedidoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProductoPorId", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class eliminarProductoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idProducto;
        
        public eliminarProductoPorIdRequest() {
        }
        
        public eliminarProductoPorIdRequest(long idProducto) {
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProductoPorIdResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class eliminarProductoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public eliminarProductoPorIdResponse() {
        }
        
        public eliminarProductoPorIdResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarPrecioVentaProducto", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class actualizarPrecioVentaProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GUI1.Sw_Pro.producto producto;
        
        public actualizarPrecioVentaProductoRequest() {
        }
        
        public actualizarPrecioVentaProductoRequest(GUI1.Sw_Pro.producto producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarPrecioVentaProductoResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class actualizarPrecioVentaProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public actualizarPrecioVentaProductoResponse() {
        }
        
        public actualizarPrecioVentaProductoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosPorNombre", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class listarProductosPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public listarProductosPorNombreRequest() {
        }
        
        public listarProductosPorNombreRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosPorNombreResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class listarProductosPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GUI1.Sw_Pro.producto[] @return;
        
        public listarProductosPorNombreResponse() {
        }
        
        public listarProductosPorNombreResponse(GUI1.Sw_Pro.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarOrden", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class actualizarOrdenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idPedido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short cantidad;
        
        public actualizarOrdenRequest() {
        }
        
        public actualizarOrdenRequest(long idPedido, long idProducto, short cantidad) {
            this.idPedido = idPedido;
            this.idProducto = idProducto;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarOrdenResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class actualizarOrdenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public actualizarOrdenResponse() {
        }
        
        public actualizarOrdenResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProducto", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class obtenerProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idProducto;
        
        public obtenerProductoRequest() {
        }
        
        public obtenerProductoRequest(long idProducto) {
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProductoResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class obtenerProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GUI1.Sw_Pro.producto @return;
        
        public obtenerProductoResponse() {
        }
        
        public obtenerProductoResponse(GUI1.Sw_Pro.producto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarProductoPedido", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class buscarProductoPedidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idPedido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idProducto;
        
        public buscarProductoPedidoRequest() {
        }
        
        public buscarProductoPedidoRequest(long idPedido, long idProducto) {
            this.idPedido = idPedido;
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarProductoPedidoResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class buscarProductoPedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GUI1.Sw_Pro.productosPedidos @return;
        
        public buscarProductoPedidoResponse() {
        }
        
        public buscarProductoPedidoResponse(GUI1.Sw_Pro.productosPedidos @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarProducto", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class guardarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GUI1.Sw_Pro.producto producto;
        
        public guardarProductoRequest() {
        }
        
        public guardarProductoRequest(GUI1.Sw_Pro.producto producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarProductoResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class guardarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public guardarProductoResponse() {
        }
        
        public guardarProductoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenes", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class listarOrdenesRequest {
        
        public listarOrdenesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class listarOrdenesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GUI1.Sw_Pro.productosPedidos[] @return;
        
        public listarOrdenesResponse() {
        }
        
        public listarOrdenesResponse(GUI1.Sw_Pro.productosPedidos[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SWControladorChannel : GUI1.Sw_Pro.SWControlador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWControladorClient : System.ServiceModel.ClientBase<GUI1.Sw_Pro.SWControlador>, GUI1.Sw_Pro.SWControlador {
        
        public SWControladorClient() {
        }
        
        public SWControladorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWControladorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWControladorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWControladorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.listarOrdenesPorIdProductoResponse GUI1.Sw_Pro.SWControlador.listarOrdenesPorIdProducto(GUI1.Sw_Pro.listarOrdenesPorIdProductoRequest request) {
            return base.Channel.listarOrdenesPorIdProducto(request);
        }
        
        public GUI1.Sw_Pro.productosPedidos[] listarOrdenesPorIdProducto(long idProducto) {
            GUI1.Sw_Pro.listarOrdenesPorIdProductoRequest inValue = new GUI1.Sw_Pro.listarOrdenesPorIdProductoRequest();
            inValue.idProducto = idProducto;
            GUI1.Sw_Pro.listarOrdenesPorIdProductoResponse retVal = ((GUI1.Sw_Pro.SWControlador)(this)).listarOrdenesPorIdProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.listarOrdenesPorIdProductoResponse> GUI1.Sw_Pro.SWControlador.listarOrdenesPorIdProductoAsync(GUI1.Sw_Pro.listarOrdenesPorIdProductoRequest request) {
            return base.Channel.listarOrdenesPorIdProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.listarOrdenesPorIdProductoResponse> listarOrdenesPorIdProductoAsync(long idProducto) {
            GUI1.Sw_Pro.listarOrdenesPorIdProductoRequest inValue = new GUI1.Sw_Pro.listarOrdenesPorIdProductoRequest();
            inValue.idProducto = idProducto;
            return ((GUI1.Sw_Pro.SWControlador)(this)).listarOrdenesPorIdProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.eliminarOrdenPorIdResponse GUI1.Sw_Pro.SWControlador.eliminarOrdenPorId(GUI1.Sw_Pro.eliminarOrdenPorIdRequest request) {
            return base.Channel.eliminarOrdenPorId(request);
        }
        
        public bool eliminarOrdenPorId(long idPedido, long idProducto) {
            GUI1.Sw_Pro.eliminarOrdenPorIdRequest inValue = new GUI1.Sw_Pro.eliminarOrdenPorIdRequest();
            inValue.idPedido = idPedido;
            inValue.idProducto = idProducto;
            GUI1.Sw_Pro.eliminarOrdenPorIdResponse retVal = ((GUI1.Sw_Pro.SWControlador)(this)).eliminarOrdenPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.eliminarOrdenPorIdResponse> GUI1.Sw_Pro.SWControlador.eliminarOrdenPorIdAsync(GUI1.Sw_Pro.eliminarOrdenPorIdRequest request) {
            return base.Channel.eliminarOrdenPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.eliminarOrdenPorIdResponse> eliminarOrdenPorIdAsync(long idPedido, long idProducto) {
            GUI1.Sw_Pro.eliminarOrdenPorIdRequest inValue = new GUI1.Sw_Pro.eliminarOrdenPorIdRequest();
            inValue.idPedido = idPedido;
            inValue.idProducto = idProducto;
            return ((GUI1.Sw_Pro.SWControlador)(this)).eliminarOrdenPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.guardarProductoPedidoResponse GUI1.Sw_Pro.SWControlador.guardarProductoPedido(GUI1.Sw_Pro.guardarProductoPedidoRequest request) {
            return base.Channel.guardarProductoPedido(request);
        }
        
        public bool guardarProductoPedido(GUI1.Sw_Pro.productosPedidos productoPedido) {
            GUI1.Sw_Pro.guardarProductoPedidoRequest inValue = new GUI1.Sw_Pro.guardarProductoPedidoRequest();
            inValue.productoPedido = productoPedido;
            GUI1.Sw_Pro.guardarProductoPedidoResponse retVal = ((GUI1.Sw_Pro.SWControlador)(this)).guardarProductoPedido(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.guardarProductoPedidoResponse> GUI1.Sw_Pro.SWControlador.guardarProductoPedidoAsync(GUI1.Sw_Pro.guardarProductoPedidoRequest request) {
            return base.Channel.guardarProductoPedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.guardarProductoPedidoResponse> guardarProductoPedidoAsync(GUI1.Sw_Pro.productosPedidos productoPedido) {
            GUI1.Sw_Pro.guardarProductoPedidoRequest inValue = new GUI1.Sw_Pro.guardarProductoPedidoRequest();
            inValue.productoPedido = productoPedido;
            return ((GUI1.Sw_Pro.SWControlador)(this)).guardarProductoPedidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.eliminarProductoPorIdResponse GUI1.Sw_Pro.SWControlador.eliminarProductoPorId(GUI1.Sw_Pro.eliminarProductoPorIdRequest request) {
            return base.Channel.eliminarProductoPorId(request);
        }
        
        public bool eliminarProductoPorId(long idProducto) {
            GUI1.Sw_Pro.eliminarProductoPorIdRequest inValue = new GUI1.Sw_Pro.eliminarProductoPorIdRequest();
            inValue.idProducto = idProducto;
            GUI1.Sw_Pro.eliminarProductoPorIdResponse retVal = ((GUI1.Sw_Pro.SWControlador)(this)).eliminarProductoPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.eliminarProductoPorIdResponse> GUI1.Sw_Pro.SWControlador.eliminarProductoPorIdAsync(GUI1.Sw_Pro.eliminarProductoPorIdRequest request) {
            return base.Channel.eliminarProductoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.eliminarProductoPorIdResponse> eliminarProductoPorIdAsync(long idProducto) {
            GUI1.Sw_Pro.eliminarProductoPorIdRequest inValue = new GUI1.Sw_Pro.eliminarProductoPorIdRequest();
            inValue.idProducto = idProducto;
            return ((GUI1.Sw_Pro.SWControlador)(this)).eliminarProductoPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.actualizarPrecioVentaProductoResponse GUI1.Sw_Pro.SWControlador.actualizarPrecioVentaProducto(GUI1.Sw_Pro.actualizarPrecioVentaProductoRequest request) {
            return base.Channel.actualizarPrecioVentaProducto(request);
        }
        
        public bool actualizarPrecioVentaProducto(GUI1.Sw_Pro.producto producto) {
            GUI1.Sw_Pro.actualizarPrecioVentaProductoRequest inValue = new GUI1.Sw_Pro.actualizarPrecioVentaProductoRequest();
            inValue.producto = producto;
            GUI1.Sw_Pro.actualizarPrecioVentaProductoResponse retVal = ((GUI1.Sw_Pro.SWControlador)(this)).actualizarPrecioVentaProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.actualizarPrecioVentaProductoResponse> GUI1.Sw_Pro.SWControlador.actualizarPrecioVentaProductoAsync(GUI1.Sw_Pro.actualizarPrecioVentaProductoRequest request) {
            return base.Channel.actualizarPrecioVentaProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.actualizarPrecioVentaProductoResponse> actualizarPrecioVentaProductoAsync(GUI1.Sw_Pro.producto producto) {
            GUI1.Sw_Pro.actualizarPrecioVentaProductoRequest inValue = new GUI1.Sw_Pro.actualizarPrecioVentaProductoRequest();
            inValue.producto = producto;
            return ((GUI1.Sw_Pro.SWControlador)(this)).actualizarPrecioVentaProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.listarProductosPorNombreResponse GUI1.Sw_Pro.SWControlador.listarProductosPorNombre(GUI1.Sw_Pro.listarProductosPorNombreRequest request) {
            return base.Channel.listarProductosPorNombre(request);
        }
        
        public GUI1.Sw_Pro.producto[] listarProductosPorNombre(string arg0) {
            GUI1.Sw_Pro.listarProductosPorNombreRequest inValue = new GUI1.Sw_Pro.listarProductosPorNombreRequest();
            inValue.arg0 = arg0;
            GUI1.Sw_Pro.listarProductosPorNombreResponse retVal = ((GUI1.Sw_Pro.SWControlador)(this)).listarProductosPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.listarProductosPorNombreResponse> GUI1.Sw_Pro.SWControlador.listarProductosPorNombreAsync(GUI1.Sw_Pro.listarProductosPorNombreRequest request) {
            return base.Channel.listarProductosPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.listarProductosPorNombreResponse> listarProductosPorNombreAsync(string arg0) {
            GUI1.Sw_Pro.listarProductosPorNombreRequest inValue = new GUI1.Sw_Pro.listarProductosPorNombreRequest();
            inValue.arg0 = arg0;
            return ((GUI1.Sw_Pro.SWControlador)(this)).listarProductosPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.actualizarOrdenResponse GUI1.Sw_Pro.SWControlador.actualizarOrden(GUI1.Sw_Pro.actualizarOrdenRequest request) {
            return base.Channel.actualizarOrden(request);
        }
        
        public bool actualizarOrden(long idPedido, long idProducto, short cantidad) {
            GUI1.Sw_Pro.actualizarOrdenRequest inValue = new GUI1.Sw_Pro.actualizarOrdenRequest();
            inValue.idPedido = idPedido;
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            GUI1.Sw_Pro.actualizarOrdenResponse retVal = ((GUI1.Sw_Pro.SWControlador)(this)).actualizarOrden(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.actualizarOrdenResponse> GUI1.Sw_Pro.SWControlador.actualizarOrdenAsync(GUI1.Sw_Pro.actualizarOrdenRequest request) {
            return base.Channel.actualizarOrdenAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.actualizarOrdenResponse> actualizarOrdenAsync(long idPedido, long idProducto, short cantidad) {
            GUI1.Sw_Pro.actualizarOrdenRequest inValue = new GUI1.Sw_Pro.actualizarOrdenRequest();
            inValue.idPedido = idPedido;
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            return ((GUI1.Sw_Pro.SWControlador)(this)).actualizarOrdenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.obtenerProductoResponse GUI1.Sw_Pro.SWControlador.obtenerProducto(GUI1.Sw_Pro.obtenerProductoRequest request) {
            return base.Channel.obtenerProducto(request);
        }
        
        public GUI1.Sw_Pro.producto obtenerProducto(long idProducto) {
            GUI1.Sw_Pro.obtenerProductoRequest inValue = new GUI1.Sw_Pro.obtenerProductoRequest();
            inValue.idProducto = idProducto;
            GUI1.Sw_Pro.obtenerProductoResponse retVal = ((GUI1.Sw_Pro.SWControlador)(this)).obtenerProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.obtenerProductoResponse> GUI1.Sw_Pro.SWControlador.obtenerProductoAsync(GUI1.Sw_Pro.obtenerProductoRequest request) {
            return base.Channel.obtenerProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.obtenerProductoResponse> obtenerProductoAsync(long idProducto) {
            GUI1.Sw_Pro.obtenerProductoRequest inValue = new GUI1.Sw_Pro.obtenerProductoRequest();
            inValue.idProducto = idProducto;
            return ((GUI1.Sw_Pro.SWControlador)(this)).obtenerProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.buscarProductoPedidoResponse GUI1.Sw_Pro.SWControlador.buscarProductoPedido(GUI1.Sw_Pro.buscarProductoPedidoRequest request) {
            return base.Channel.buscarProductoPedido(request);
        }
        
        public GUI1.Sw_Pro.productosPedidos buscarProductoPedido(long idPedido, long idProducto) {
            GUI1.Sw_Pro.buscarProductoPedidoRequest inValue = new GUI1.Sw_Pro.buscarProductoPedidoRequest();
            inValue.idPedido = idPedido;
            inValue.idProducto = idProducto;
            GUI1.Sw_Pro.buscarProductoPedidoResponse retVal = ((GUI1.Sw_Pro.SWControlador)(this)).buscarProductoPedido(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.buscarProductoPedidoResponse> GUI1.Sw_Pro.SWControlador.buscarProductoPedidoAsync(GUI1.Sw_Pro.buscarProductoPedidoRequest request) {
            return base.Channel.buscarProductoPedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.buscarProductoPedidoResponse> buscarProductoPedidoAsync(long idPedido, long idProducto) {
            GUI1.Sw_Pro.buscarProductoPedidoRequest inValue = new GUI1.Sw_Pro.buscarProductoPedidoRequest();
            inValue.idPedido = idPedido;
            inValue.idProducto = idProducto;
            return ((GUI1.Sw_Pro.SWControlador)(this)).buscarProductoPedidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.guardarProductoResponse GUI1.Sw_Pro.SWControlador.guardarProducto(GUI1.Sw_Pro.guardarProductoRequest request) {
            return base.Channel.guardarProducto(request);
        }
        
        public bool guardarProducto(GUI1.Sw_Pro.producto producto) {
            GUI1.Sw_Pro.guardarProductoRequest inValue = new GUI1.Sw_Pro.guardarProductoRequest();
            inValue.producto = producto;
            GUI1.Sw_Pro.guardarProductoResponse retVal = ((GUI1.Sw_Pro.SWControlador)(this)).guardarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.guardarProductoResponse> GUI1.Sw_Pro.SWControlador.guardarProductoAsync(GUI1.Sw_Pro.guardarProductoRequest request) {
            return base.Channel.guardarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.guardarProductoResponse> guardarProductoAsync(GUI1.Sw_Pro.producto producto) {
            GUI1.Sw_Pro.guardarProductoRequest inValue = new GUI1.Sw_Pro.guardarProductoRequest();
            inValue.producto = producto;
            return ((GUI1.Sw_Pro.SWControlador)(this)).guardarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI1.Sw_Pro.listarOrdenesResponse GUI1.Sw_Pro.SWControlador.listarOrdenes(GUI1.Sw_Pro.listarOrdenesRequest request) {
            return base.Channel.listarOrdenes(request);
        }
        
        public GUI1.Sw_Pro.productosPedidos[] listarOrdenes() {
            GUI1.Sw_Pro.listarOrdenesRequest inValue = new GUI1.Sw_Pro.listarOrdenesRequest();
            GUI1.Sw_Pro.listarOrdenesResponse retVal = ((GUI1.Sw_Pro.SWControlador)(this)).listarOrdenes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI1.Sw_Pro.listarOrdenesResponse> GUI1.Sw_Pro.SWControlador.listarOrdenesAsync(GUI1.Sw_Pro.listarOrdenesRequest request) {
            return base.Channel.listarOrdenesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI1.Sw_Pro.listarOrdenesResponse> listarOrdenesAsync() {
            GUI1.Sw_Pro.listarOrdenesRequest inValue = new GUI1.Sw_Pro.listarOrdenesRequest();
            return ((GUI1.Sw_Pro.SWControlador)(this)).listarOrdenesAsync(inValue);
        }
    }
}
